export type Location = {
  slug: string;
  name: string;
  address: string;
  city: string;
  region: string;
  postalCode: string;
  phone?: string;
  phoneHref?: string;
  website?: string;
  mapUrl: string;
};

export const locations: Location[] = [
  {
    slug: 'rpt-clinic-troy-mi',
    name: 'Robotic Precision Therapy Clinic',
    address: '3250 W Big Beaver Road, Suite 426',
    city: 'Troy',
    region: 'MI',
    postalCode: '48084',
    phone: '(855) 629-2805',
    phoneHref: '+18556292805',
    website: 'https://rptclinic.com/',
    mapUrl: 'https://maps.app.goo.gl/pGJ9ox5sqRmwnmCB8',
  },
  {
    slug: 'advanced-robotic-therapy-rochester-mi',
    name: 'Advanced Robotic Therapy',
    address: '251 Diversion Street, Suite 102',
    city: 'Rochester',
    region: 'MI',
    postalCode: '48307',
    phone: '(248) 918-2611',
    phoneHref: '+12489182611',
    website: 'https://advancedrtclinic.com/',
    mapUrl: 'https://maps.app.goo.gl/F7fMh1is7aKoapmU6',
  },
  {
    slug: 'complete-care-chiropractic-warren-mi',
    name: 'Complete Care Chiropractic',
    address: '30061 Schoenherr Road, Suite B',
    city: 'Warren',
    region: 'MI',
    postalCode: '48088',
    phone: '(586) 576-0701',
    phoneHref: '+15865760701',
    website: 'https://completewellnesscare.com/',
    mapUrl: 'https://maps.app.goo.gl/YB7Wty8z3EocRQscA',
  },
  {
    slug: 'empower-pt-and-fitness-bloomfield-hills-mi',
    name: 'Empower PT and Fitness',
    address: '53 W Long Lake Road',
    city: 'Bloomfield Hills',
    region: 'MI',
    postalCode: '48304',
    phone: '(248) 742-7000',
    phoneHref: '+12487427000',
    website: 'https://empowerptandfitness.com/',
    mapUrl: 'https://maps.app.goo.gl/kTxHUk54U16c2mTKA',
  },
  {
    slug: 'empower-pt-clinton-township-mi',
    name: 'Empower PT in Clinton Twp',
    address: '20554 Hall Road',
    city: 'Clinton Township',
    region: 'MI',
    postalCode: '48038',
    phone: '(586) 868-7000',
    phoneHref: '+15868687000',
    website: 'https://empowerptandfitness.com/',
    mapUrl: 'https://maps.app.goo.gl/SSriWevpHWyWniH36',
  },
  {
    slug: 'healed-beyond-hope-millington-mi',
    name: 'Healed Beyond Hope',
    address: '8501 State Street',
    city: 'Millington',
    region: 'MI',
    postalCode: '48746',
    phone: '(810) 285-0894',
    phoneHref: '+18102850894',
    website: 'https://healedbeyondhope.solutions/',
    mapUrl: 'https://maps.app.goo.gl/tQGbgxgpvmh8Hm2cA',
  },
  {
    slug: 'leading-edge-physical-therapy-lakeland-fl',
    name: 'Leading Edge Physical Therapy',
    address: '500 Florida Avenue S, Suite 620',
    city: 'Lakeland',
    region: 'FL',
    postalCode: '33801',
    phone: '(863) 688-1800',
    phoneHref: '+18636881800',
    website: 'https://leadingedgepolk.com/',
    mapUrl: 'https://maps.app.goo.gl/crBnTBqBRLsdBUm77',
  },
  {
    slug: 'livewell-clarkston-mi',
    name: 'LiveWell',
    address: '7138 Sashabaw Road',
    city: 'Village of Clarkston',
    region: 'MI',
    postalCode: '48348',
    phone: '(248) 771-5000',
    phoneHref: '+12487715000',
    website: 'https://livewellrtc.com/',
    mapUrl: 'https://maps.app.goo.gl/5z3BeYHGGiHacYGt5',
  },
  {
    slug: 'naples-robotic-pain-relief-naples-fl',
    name: 'Naples Robotic Pain Relief',
    address: '5625 Strand Boulevard, Suite 508',
    city: 'Naples',
    region: 'FL',
    postalCode: '34110',
    phone: '(239) 778-6842',
    phoneHref: '+12397786842',
    website: 'https://naplesroboticpainrelief.com/',
    mapUrl: 'https://maps.app.goo.gl/tNXKJ2Vybfs9sW3u5',
  },
  {
    slug: 'robotic-wellness-pinecrest-fl',
    name: 'Robotic Wellness',
    address: '9655 S Dixie Highway, Suite 111',
    city: 'Pinecrest',
    region: 'FL',
    postalCode: '33156',
    phone: '(305) 360-4999',
    phoneHref: '+13053604999',
    website: 'https://roboticwellnessllc.com/',
    mapUrl: 'https://maps.app.goo.gl/JB779gxDw4psDpVG6',
  },
  {
    slug: 'structure-function-chiropractic-traverse-city-mi',
    name: 'Structure & Function Chiropractic & Rehab',
    address: '120 Boardman Avenue',
    city: 'Traverse City',
    region: 'MI',
    postalCode: '49684',
    phone: '(231) 421-3968',
    phoneHref: '+12314213968',
    website: 'https://www.sfchirotc.com/',
    mapUrl: 'https://maps.app.goo.gl/YokLJMs8ohtqHbiW7',
  },
  {
    slug: 'thera-performance-lab-lake-orion-mi',
    name: 'Thera Performance Lab',
    address: '146 S Broadway, Suite 160',
    city: 'Lake Orion',
    region: 'MI',
    postalCode: '48362',
    phone: '(248) 690-5444',
    phoneHref: '+12486905444',
    website: 'https://www.thera-performancelab.com/',
    mapUrl: 'https://maps.app.goo.gl/cJgU116zGjxUR6h68',
  },
  {
    slug: 'theramax-miami-fl',
    name: 'TheraMax',
    address: '2353 Coral Way',
    city: 'Miami',
    region: 'FL',
    postalCode: '33145',
    phone: '(305) 849-6117',
    phoneHref: '+13058496117',
    website: 'https://theramax.com/',
    mapUrl: 'https://maps.app.goo.gl/gNcz7UangUfDSZHX7',
  },
  {
    slug: 'total-body-rehab-trenton-mi',
    name: 'Total Body Rehab',
    address: '2189 West Road',
    city: 'Trenton',
    region: 'MI',
    postalCode: '48183',
    phone: '(734) 307-3670',
    phoneHref: '+17343073670',
    website: 'https://tbrphysicaltherapy.com/',
    mapUrl: 'https://maps.app.goo.gl/e8L1gwgfsQoNnNmw9',
  },
  {
    slug: 'truwell-physical-therapy-brighton-mi',
    name: 'TruWell Physical Therapy | Brighton',
    address: '7600 Grand River Avenue',
    city: 'Brighton',
    region: 'MI',
    postalCode: '48114',
    phone: '(810) 306-2626',
    phoneHref: '+18103062626',
    website: 'https://www.truwellphysicaltherapy.com/',
    mapUrl: 'https://maps.app.goo.gl/wzkjWwQGpoMAcbPP6',
  },
  {
    slug: 'truwell-physical-therapy-commerce-mi',
    name: 'TruWell Physical Therapy | Commerce',
    address: '2655 Oakley Park Road',
    city: 'Commerce Township',
    region: 'MI',
    postalCode: '48390',
    phone: '(248) 716-1819',
    phoneHref: '+12487161819',
    website: 'https://truwellphysicaltherapy.com/',
    mapUrl: 'https://maps.app.goo.gl/DTAgSsW2JBGNpK9F6',
  },
];
